### ISSUE TITLE
Failed to Update View server

### ISSUE THREAD

**Issue by sspankaj** [flectrahq/flectra#19]
Impacted versions:
Flectra 1
Steps to reproduce:
open to edit any existing module in app builder i.e. to edit model.
Current behavior:
Failed to Update View server
Expected behavior:
drag and drop any field 
Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/29782180/34351731-7ee86e3a-ea44-11e7-9611-40765afe82e8.png)

**Comment by Jungi-Flectra** [comment]
please provide error log also it would be great if you specify steps in detail that would be enough for us to know what is causing error thank you for reporting.

**Comment by sspankaj** [comment]
steps-
sales --->quotation-> edit than run app_builder to add any field ....
**log error**
2017-12-26 08:59:13,878 2884 ERROR odoo380 flectra.service.server: Exception happened during processing of request from ('127.0.0.1', 52185)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 283, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])

**Comment by sspankaj** [comment]
one more error if create new app through app_builder
![image](https://user-images.githubusercontent.com/29782180/34353367-b316f3bc-ea4d-11e7-8691-92878d097502.png)


**and log -**

Traceback (most recent call last):
  File "D:\flectra1.0\flectra\flectra\http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\flectra1.0\flectra\flectra\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\flectra1.0\flectra\flectra\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "D:\flectra1.0\flectra\flectra\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\flectra1.0\flectra\flectra\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\flectra1.0\flectra\flectra\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\flectra1.0\flectra\flectra\http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "D:\flectra1.0\flectra\flectra\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "D:\flectra1.0\flectra\addons\web\controllers\builder\main.py", line 513, in create_new_app
    'licence': licence})
  File "D:\flectra1.0\flectra\flectra\models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "D:\flectra1.0\flectra\flectra\models.py", line 3350, in _create
    column_val = field.convert_to_column(val, self, vals)
  File "D:\flectra1.0\flectra\flectra\fields.py", line 1218, in convert_to_column
    result = float(value or 0.0)
ValueError: could not convert string to float: TEST APP

**Comment by sb-flectra** [comment]
https://github.com/flectrahq/flectra/pull/26

**Comment by niulinlnc** [comment]
Dear @sb-flectra 
The problem remains, and has not been solved completely.

**Comment by sspankaj** [comment]
@sb-flectra  yes!..error not resolve completely .

**Comment by sb-flectra** [comment]
Hello, @sspankaj & @niulinlnc 

Sorry for the inconvenience, As at the time of that PR's merge that both issues is not reproducing, So, I closed the issue.

But I'm sure that your 2nd issue, `ValueError: could not convert string to float: TEST APP` at the time of creating the new app from app builder is not anymore reproducible with the latest code.

As we are trying to solve your other issues, also I'll reopen this issue.

Again thanks. :smile:

**Comment by Jungi-Flectra** [comment]
@sspankaj @niulinlnc  The issue has been fixed please take pull of latest commit and check the same with latest code. thank you.

**Comment by sspankaj** [comment]
working fine with latest code except not able to set app icon..
![image](https://user-images.githubusercontent.com/29782180/34403206-e9c04eb0-ebcc-11e7-8fdb-a5262d87bfbc.png)

**Comment by sb-flectra** [comment]
Hi, Icon issue is just merge in `master` & `1.0` with commit ref. 2bfde4217c6bb72bea55bcbb715556a147dd3b6c
