### ISSUE TITLE
Error while running with quality or project scrum module

### ISSUE THREAD

**Issue by rachmataditiya** [flectrahq/flectra#3]
Impacted versions:
1.0
Steps to reproduce:
Installing Quality module and Project scrum module
Current behavior:
`
Error:
Uncaught Error: QWeb2 - template['AppsLauncher.Menus']: Runtime Error: TypeError: dict.dashboard_app.action.split is not a function

http://localhost:7073/web/content/322-243b12c/web.assets_common.js:3689
Traceback:
Error: QWeb2 - template['AppsLauncher.Menus']: Runtime Error: TypeError: dict.dashboard_app.action.split is not a function
    at Object.exception (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:3689:7)
    at Engine.eval (eval at _render (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:3731:73), <anonymous>:34:29)
    at Engine._render (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:3730:296)
    at Engine.render (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:3730:151)
    at Object.<anonymous> (http://localhost:7073/web/content/329-8091eb9/web.assets_backend.js:821:946)
    at Object.<anonymous> (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:802:681)
    at fire (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:801:198)
    at Object.<anonymous> (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:802:874)
    at fire (http://localhost:7073/web/content/322-243b12c/web.assets_common.js:796:299)
`
Expected behavior:

Video/Screenshot link (optional):
![screen shot 1439-04-07 at 21 19 41](https://user-images.githubusercontent.com/32624220/34340586-787454d2-e9b9-11e7-8623-758ab9de6d41.png)

**Comment by malatestay** [comment]
Same issue

**Comment by chintanambaliya-flectra** [comment]
Issue fixed with #12 PR
