### ISSUE TITLE
External ID not found in the system: project_scrum.demo_project_1

### ISSUE THREAD

**Issue by tarikelkbich** [flectrahq/flectra#31]
Impacted versions: v1

Steps to reproduce: install project_scrum with demo data

Current behavior: External ID not found in the system: project_scrum.demo_project_1

Expected behavior: installation with no issues

Video/Screenshot link (optional):

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/flectra/flectra/flectra/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f03bc4b7048>, 'project_scrum.demo_project_1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1415, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-22>", line 2, in xmlid_lookup
  File "/opt/flectra/flectra/flectra/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1404, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: project_scrum.demo_project_1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/modules/registry.py", line 85, in new
    flectra.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1415, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-22>", line 2, in xmlid_lookup
  File "/opt/flectra/flectra/flectra/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1404, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
flectra.tools.convert.ParseError: "External ID not found in the system: project_scrum.demo_project_1" while parsing /opt/flectra/flectra/addons/project_scrum/demo/project_team_demo.xml:26, near
<record id="project_team_1" model="project.team">
            <field name="name">Project Module Team</field>
            <field name="project_id" ref="project_scrum.demo_project_1"/>
            <field name="member_ids" eval="[(6, 0, [ref('project_scrum.user_1'), ref('project_scrum.user_2')])]"/>
            <field name="master_id" ref="project_scrum.user_1"/>
            <field name="branch_id" ref="base_branch_company.data_branch_1"/>
            <field name="strength">Technical, Functional</field>
            <field name="description">Description for the Project team...</field>
        </record>
2017-12-22 19:42:00,117 9321 ERROR FLECTRA_DEMO flectra.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/flectra/flectra/flectra/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f03bc4b7048>, 'project_scrum.demo_project_1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1415, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-22>", line 2, in xmlid_lookup
  File "/opt/flectra/flectra/flectra/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1404, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: project_scrum.demo_project_1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/flectra/flectra/flectra/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/flectra/flectra/flectra/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/flectra/flectra/flectra/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 974, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 962, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/flectra/flectra/addons/website/models/module.py", line 24, in button_immediate_install
    return super(IrModuleModule, self).button_immediate_install()
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/flectra/flectra/flectra/modules/registry.py", line 85, in new
    flectra.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 639, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 724, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 730, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1415, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-22>", line 2, in xmlid_lookup
  File "/opt/flectra/flectra/flectra/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1404, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
flectra.tools.convert.ParseError: "External ID not found in the system: project_scrum.demo_project_1" while parsing /opt/flectra/flectra/addons/project_scrum/demo/project_team_demo.xml:26, near
<record id="project_team_1" model="project.team">
            <field name="name">Project Module Team</field>
            <field name="project_id" ref="project_scrum.demo_project_1"/>
            <field name="member_ids" eval="[(6, 0, [ref('project_scrum.user_1'), ref('project_scrum.user_2')])]"/>
            <field name="master_id" ref="project_scrum.user_1"/>
            <field name="branch_id" ref="base_branch_company.data_branch_1"/>
            <field name="strength">Technical, Functional</field>
            <field name="description">Description for the Project team...</field>
        </record>

**Comment by sb-flectra** [comment]
@tarikelkbich 

Thanks for reporting the issue, As I've just checked this issue in my machine, but I'm unable to reproduce it(with or without demo-data) when installing `project_scrum` module.

`project_scrum` was installed without any issues!!

So, I suggest you that, test it with latest code, maybe take new clone of the branch (master or 1.0)!!

And still the same issue occurs again feel free to reopen this issue.

Thanks.
