### ISSUE TITLE
Uncaught TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by niulinlnc** [flectrahq/flectra#32]
error when close app builder

Error:
Uncaught TypeError: Object.values is not a function

http://127.0.0.1:8011/web/content/409-6610366/web.assets_backend.js:2057
Traceback:
TypeError: Object.values is not a function
    at FlectraClass.<anonymous> (http://127.0.0.1:8011/web/content/409-6610366/web.assets_backend.js:2057:500)
    at FlectraClass.trigger (http://127.0.0.1:8011/web/content/397-b06dfe0/web.assets_common.js:3915:180)
    at FlectraClass.trigger (http://127.0.0.1:8011/web/content/397-b06dfe0/web.assets_common.js:3921:148)
    at HTMLButtonElement.<anonymous> (http://127.0.0.1:8011/web/content/409-6610366/web.assets_backend.js:2082:974)
    at HTMLBodyElement.dispatch (http://127.0.0.1:8011/web/content/397-b06dfe0/web.assets_common.js:892:451)
    at HTMLBodyElement.elemData.handle (http://127.0.0.1:8011/web/content/397-b06dfe0/web.assets_common.js:865:173)

**Comment by Jungi-Flectra** [comment]
The links that you provide is localhost address which is inaccessible for us. please send steps to reproduce the error in order to fix it or kindly send full error log.Thank You for reporting.

**Comment by niulinlnc** [comment]
This error occurs whenever I switch to the app builder mode and drop out of the app builder.
And you can check out my test site
User name demo, password demo
The full error is:
Error:
Uncaught TypeError: Object.values is not a function

https://www.opencap.cn/web/content/255-77806fc/web.assets_backend.js:2057
Traceback:
TypeError: Object.values is not a function
    at FlectraClass.<anonymous> (https://www.opencap.cn/web/content/255-77806fc/web.assets_backend.js:2057:500)
    at FlectraClass.trigger (https://www.opencap.cn/web/content/244-2a13434/web.assets_common.js:3915:180)
    at FlectraClass.trigger (https://www.opencap.cn/web/content/244-2a13434/web.assets_common.js:3921:148)
    at HTMLButtonElement.<anonymous> (https://www.opencap.cn/web/content/255-77806fc/web.assets_backend.js:2082:974)
    at HTMLBodyElement.dispatch (https://www.opencap.cn/web/content/244-2a13434/web.assets_common.js:892:451)
    at HTMLBodyElement.elemData.handle (https://www.opencap.cn/web/content/244-2a13434/web.assets_common.js:865:173)
![default](https://user-images.githubusercontent.com/11767049/34371682-398b749c-eb0a-11e7-8f82-7e5de33eef58.jpg)

**Comment by sb-flectra** [comment]
@niulinlnc ,

As per you instruction, I've already test this issue in your test site.
Here are the steps that I followed...
- Go to Contacts / Contacts / Open form view
- Now clicked on App Builder Icon (which will open app builder UI)
- Now just click on close icon which will close the app builder UI.

For the above steps I'm unable to reproduce your error.
So, can you please more elaborate on this?

Thanks.

**Comment by niulinlnc** [comment]
Dear @sb-flectra 
Thank you for your reply, I found that the problem was caused by the version of Google browser,
If I use the other web browsers（ based on Google browser kernel version 53 or less）, this error will be made. with the latest Google kernel 62, which will not go wrong.

**Comment by sb-flectra** [comment]
Yes, you are right.
Ref. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

As, We suggest that use updated browser.  :smile_cat:
