### ISSUE TITLE
Installing Website builder fails updating database

### ISSUE THREAD

**Issue by deajan** [flectrahq/flectra#41]
Impacted versions: Current git master as of 27/12/2017 2pm UTC+C

Steps to reproduce: Install Website Builder

Current behavior: Installs, but fails updating database

Expected behavior:

Log export:
```
2017-12-27 14:08:50,097 26002 INFO db_preprod flectra.modules.registry: module website: creating or updating database tables
2017-12-27 14:08:50,272 26002 INFO db_preprod flectra.models: Computing parent left and right for table website_menu...
2017-12-27 14:08:50,430 26002 ERROR db_preprod flectra.sql_db: bad query: b'ALTER TABLE "res_config_settings" ALTER COLUMN "website_id" SET NOT NULL'
ERROR: ERREUR:  la colonne « website_id » contient des valeurs NULL

2017-12-27 14:08:50,431 26002 WARNING db_preprod flectra.schema: Table 'res_config_settings': unable to set NOT NULL on column 'website_id'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "res_config_settings" ALTER COLUMN "website_id" SET NOT NULL
Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/tools/sql.py", line 109, in set_not_null
    cr.execute(query)
  File "/opt/flectra/flectra/flectra/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: ERREUR:  la colonne « website_id » contient des valeurs NULL
```

**Comment by sb-flectra** [comment]
@deajan 

Can you please provide me the steps to reproduce? As I'm unable to reproduce the same with current updated code!

**Comment by deajan** [comment]
Neither can I... Started a fresh DB, installed website builder, no errors.
I cannot retrace my first tests though. Sorry.
