### ISSUE TITLE
Error on Inventory adjustment issue

### ISSUE THREAD

**Issue by BalramY** [flectrahq/flectra#55]
Impacted versions:
1.0
Steps to reproduce:
Create inventory adjustment and fill details and click on start inventory button on header.

Current behavior:
Following error- 
Error:
Flectra Server Error

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/flectra/flectra/flectra/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/flectra/flectra/flectra/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/flectra/flectra/flectra/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 974, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 962, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/flectra/flectra/addons/stock/models/stock_inventory.py", line 190, in action_start
    vals.update({'line_ids': [(0, 0, line_values) for line_values in inventory._get_inventory_lines_values()]})
  File "/opt/flectra/flectra/addons/stock/models/stock_inventory.py", line 251, in _get_inventory_lines_values
    GROUP BY product_id, location_id, lot_id, package_id, partner_id """ % domain, args)
  File "/opt/flectra/flectra/flectra/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near ")"
LINE 3:             WHERE  location_id in () AND company_id = 1 AND ...
                                           ^
Expected behavior:
do the inventory adustment
Video/Screenshot link (optional):

**Comment by pratik-flectra** [comment]
@BalramY 
Please try with new Database. As it shows there is some problem with your locations. If it still gives traceback then provide us more specific regeneration steps. Thank you for your response.

video Link :
https://drive.google.com/open?id=1k7-Z2b_PaLjMZOn3EXlAcWmsDsKJKLME

**Comment by sb-flectra** [comment]
Dear @BalramY ,

Can you please check it again with latest update of code. As I'm not able to reproduce it!!
If its still exists then feel free to re-open the issue.

Thanks.
