### ISSUE TITLE
Flectra Server Error: KeyError: 'favicon'

### ISSUE THREAD

**Issue by argitx** [flectrahq/flectra#60]
Impacted versions:
1.0
Steps to reproduce:
Install any module on a fresh database.
Current behavior:
KeyError: 'favicon'
Expected behavior:
It shouldn't
Video/Screenshot link (optional):
Error:
Flectra Server Error

Traceback (most recent call last):
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/linux/.virtualenvs/flectra/flectra/addons/web/controllers/main.py", line 974, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/linux/.virtualenvs/flectra/flectra/addons/web/controllers/main.py", line 962, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/modules/registry.py", line 85, in new
    flectra.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/modules/loading.py", line 134, in load_module_graph
    registry.setup_models(cr)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/modules/registry.py", line 279, in setup_models
    model._setup_fields()
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/models.py", line 2344, in _setup_fields
    field.setup_full(self)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/fields.py", line 481, in setup_full
    self._setup_related_full(model)
  File "/home/linux/.virtualenvs/flectra/flectra/flectra/fields.py", line 518, in _setup_related_full
    field = target._fields[name]
KeyError: 'favicon'

**Comment by nicholashosein** [comment]
I too have gotten this error whenever I try to install the Sales app.
However, installing the Website Builder app would allow the Sales app to be installed.

This is a bug as you should be able to install the Sales app without the Website Builder app being installed.

**Comment by mhdsyarif** [comment]
I too have gotten this error whenever I try to install the Sales app.
![selection_512](https://user-images.githubusercontent.com/5978109/34512677-74dae30c-f096-11e7-8411-e0bc11c24adb.png)

**Comment by sb-flectra** [comment]
Fixed with commit ref. 511d3b2329931028e4552b3524a5926a94079cfd
