### ISSUE TITLE
Install Purchase Management and Inventory Management

### ISSUE THREAD

**Issue by davidogles** [flectrahq/flectra#61]
Impacted versions:

Steps to reproduce: Flectra - Apps - Purchase Management (and Inventory Management

Current behavior: Get error installing either App

Expected behavior:

Video/Screenshot link (optional):
Error:
Flectra Server Error

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/models.py", line 967, in _validate_fields
    check(self)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 1024, in postprocess_and_fields
    self.raise_view_error("\n".join(msg_lines), view_id)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Field 'product_tmpl_id' used in attributes must be present in view but is missing:
 - 'product_tmpl_id' in domain="[('product_tmpl_id','=',product_tmpl_id)]"

Error context:
View `Stock Moves`
[view_id: 1509, xml_id: n/a, model: stock.move, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/flectra/flectra/flectra/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/flectra/flectra/flectra/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/flectra/flectra/flectra/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/flectra/flectra/flectra/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/flectra/flectra/flectra/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
flectra.exceptions.ValidationError: ('Error while validating constraint\n\nField \'product_tmpl_id\' used in attributes must be present in view but is missing:\n - \'product_tmpl_id\' in domain="[(\'product_tmpl_id\',\'=\',product_tmpl_id)]"\n\nError context:\nView `Stock Moves`\n[view_id: 1509, xml_id: n/a, model: stock.move, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/flectra/flectra/flectra/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/flectra/flectra/flectra/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/flectra/flectra/flectra/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 970, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 958, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/flectra/flectra/flectra/modules/registry.py", line 85, in new
    flectra.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/flectra/flectra/flectra/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/flectra/flectra/flectra/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/flectra/flectra/flectra/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/flectra/flectra/flectra/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/flectra/flectra/flectra/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
flectra.tools.convert.ParseError: "Error while validating constraint

Field 'product_tmpl_id' used in attributes must be present in view but is missing:
 - 'product_tmpl_id' in domain="[('product_tmpl_id','=',product_tmpl_id)]"

Error context:
View `Stock Moves`
[view_id: 1509, xml_id: n/a, model: stock.move, parent_id: n/a]
None" while parsing /opt/flectra/flectra/addons/stock/views/stock_move_views.xml:4, near
<record id="stock_move_tree" model="ir.ui.view">
            <field name="name">Stock Moves</field>
            <field name="model">stock.move</field>
            <field name="arch" type="xml">
                <tree decoration-muted="state == 'cancel'" string="Moves" create="false">
                    <field name="product_id"/>
                    <field name="product_uom_qty"/>
                    <field name="product_uom" options="{'no_open': True, 'no_create': True}" string="Unit of Measure" groups="product.group_uom"/>
                    <field name="product_packaging" domain="[('product_tmpl_id','=',product_tmpl_id)]" groups="product.group_stock_packaging"/>
                    <field name="picking_id"/>
                    <field name="location_id" groups="stock.group_stock_multi_locations"/>
                    <field name="location_dest_id" groups="stock.group_stock_multi_locations"/>
                    <field name="create_date" groups="base.group_no_one"/>
                    <field name="date" string="Date" groups="base.group_no_one"/>
                    <field name="date_expected" string="Date Expected"/>
                    <field name="state"/>
                </tree>
            </field>
        </record>

**Comment by thomich** [comment]
Hello @davidogles 

Thanks for your Report.

We could reproduce it in a fresh DB and will work on and fix it.
Stay tuned ;)

Regards
thomi
