### ISSUE TITLE
Error validate customer invoice after install module l10n_fr_certification

### ISSUE THREAD

**Issue by ythann64** [flectrahq/flectra#63]
Impacted versions: flectra1

Steps to reproduce:
Install module l10n_fr_certification
Validate customer invoice

Current behavior: TypeError: __init__() got an unexpected keyword argument 'encoding'

Expected behavior: Validation customer invoice

Video/Screenshot link (optional):

Erreur:
Flectra Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flectra/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/flectra/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <flectra.api.Environment object at 0x7f64c5eb1b70>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 974, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 962, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/flectra/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/flectra/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/flectra/flectra/addons/account/models/account_invoice.py", line 776, in action_invoice_open
    to_open_invoices.action_move_create()
  File "/opt/flectra/flectra/addons/account/models/account_invoice.py", line 1148, in action_move_create
    move.post()
  File "/opt/flectra/flectra/addons/account/models/account_move.py", line 166, in post
    return self.write({'state': 'posted'})
  File "/opt/flectra/flectra/addons/l10n_fr_certification/models/account.py", line 93, in write
    'l10n_fr_hash': move._get_new_hash(new_number)}
  File "/opt/flectra/flectra/addons/l10n_fr_certification/models/account.py", line 38, in _get_new_hash
    return self._compute_hash(prev_move.l10n_fr_hash if prev_move else '')
  File "/opt/flectra/flectra/addons/l10n_fr_certification/models/account.py", line 44, in _compute_hash
    hash_string = sha256(previous_hash + self.l10n_fr_string_to_hash)
  File "/usr/lib/python3/dist-packages/flectra/fields.py", line 948, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/flectra/fields.py", line 1059, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/flectra/fields.py", line 1015, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/flectra/fields.py", line 1006, in _compute_value
    getattr(records, self.compute)()
  File "/opt/flectra/flectra/addons/l10n_fr_certification/models/account.py", line 67, in _compute_string_to_hash
    separators=(',', ':'))
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by pratik-flectra** [comment]
Hi @ythann64 ,
As I'm unable to reproduce this error with updated code. So, I suggest you to check again with latest pull of code.
And still this issue occur then feel free to re-open issue.
Thanks.
