### ISSUE TITLE
Online proposal module installation issue

### ISSUE THREAD

**Issue by malatestay** [flectrahq/flectra#66]
Impacted versions: 1.0

Erreur:
Flectra Server Error

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/models.py", line 967, in _validate_fields
    check(self)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 1022, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 517, in raise_view_error
    raise ValueError(message)
ValueError: Le champ `module_account_reports_followup` n'existe pas

Contexte de l'erreur :
Vue `res.config.settings.view.form.inherit.website.quote`
[view_id: 2665, xml_id: n/a, model: res.config.settings, parent_id: 1338]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/flectra/flectra/addons/website/models/ir_model.py", line 95, in _update
    record = record.create(values)
  File "/opt/flectra/flectra/addons/website/models/ir_ui_view.py", line 225, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 401, in create
    res = super(View, self).create(self._compute_defaults(values))
  File "/opt/flectra/flectra/flectra/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/flectra/flectra/flectra/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 422, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/flectra/flectra/flectra/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/flectra/flectra/flectra/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/flectra/flectra/flectra/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
flectra.exceptions.ValidationError: ("Erreur lors de la validation de la contrainte\n\nLe champ `module_account_reports_followup` n'existe pas\n\nContexte de l'erreur :\nVue `res.config.settings.view.form.inherit.website.quote`\n[view_id: 2665, xml_id: n/a, model: res.config.settings, parent_id: 1338]", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flectra/flectra/flectra/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/flectra/flectra/flectra/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/flectra/flectra/flectra/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/flectra/flectra/flectra/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/flectra/flectra/flectra/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 974, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/flectra/flectra/addons/web/controllers/main.py", line 962, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/flectra/flectra/flectra/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/flectra/flectra/addons/website/models/module.py", line 24, in button_immediate_install
    return super(IrModuleModule, self).button_immediate_install()
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/flectra/flectra/flectra/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/flectra/flectra/flectra/modules/registry.py", line 85, in new
    flectra.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/flectra/flectra/flectra/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/flectra/flectra/flectra/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/flectra/flectra/flectra/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/flectra/flectra/addons/website/models/ir_model.py", line 95, in _update
    record = record.create(values)
  File "/opt/flectra/flectra/addons/website/models/ir_ui_view.py", line 225, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 401, in create
    res = super(View, self).create(self._compute_defaults(values))
  File "/opt/flectra/flectra/flectra/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/flectra/flectra/flectra/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/flectra/flectra/flectra/addons/base/ir/ir_ui_view.py", line 422, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/flectra/flectra/flectra/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/flectra/flectra/flectra/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/flectra/flectra/flectra/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
flectra.tools.convert.ParseError: "Erreur lors de la validation de la contrainte

Le champ `module_account_reports_followup` n'existe pas

Contexte de l'erreur :
Vue `res.config.settings.view.form.inherit.website.quote`
[view_id: 2665, xml_id: n/a, model: res.config.settings, parent_id: 1338]
None" while parsing /opt/flectra/flectra/addons/website_quote/views/res_config_settings_views.xml:4, near
<record id="res_config_settings_view_form" model="ir.ui.view">
        <field name="name">res.config.settings.view.form.inherit.website.quote</field>
        <field name="model">res.config.settings</field>
        <field name="inherit_id" ref="sale.res_config_settings_view_form"/>
        <field name="arch" type="xml">
            <xpath expr="//div[@id='sale_config_website_quote']" position="after">
                <div class="content-group" attrs="{'invisible': [('module_website_quote','=',False)]}">
                    <div class="mt16">
                        <label for="default_template_id" class="o_light_label"/>
                        <field name="default_template_id" class="oe_inline"/>
                    </div>
                    <div>
                        <button name="%(website_quote.action_sale_quotation_template)d" icon="fa-arrow-right" type="action" string="Quotation Templates" class="btn-link"/>
                    </div>
                 </div>
             </xpath>
        </field>
    </record>

**Comment by malatestay** [comment]
Some other module have same error:
eCommerce Delivery
Website Sale Stock - Website Delivery Information

**Comment by kaushal-flectra** [comment]
Hello @malatestay 

Can you please check it again with the latest update of code (Commit No.: f47a6271748df3bf234e7a097d035e158406b083) with new DB. As I'm not able to reproduce it!!
If it still exists then feel free to re-open the issue.

Thanks.
