### ISSUE TITLE
Error Adding New User

### ISSUE THREAD

**Issue by brandon72501** [flectrahq/flectra#69]
Impacted versions: 1

I tried to add a user, but got the following:
I got a Flectra Server Error.
What is this?

Error:
Flectra Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flectra/addons/base/ir/ir_mail_server.py", line 457, in send_email
    smtp.sendmail(smtp_from, smtp_to_list, message.as_string())
  File "/usr/lib/python3.5/smtplib.py", line 862, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [MWHPR1001CA0013.namprd10.prod.outlook.com]', 'bounce+6-res.users-10@iauctionco.com')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flectra/addons/mail/models/mail_mail.py", line 242, in send
    smtp_session=smtp_session)
  File "/usr/lib/python3/dist-packages/flectra/addons/mail/models/mail_mail.py", line 326, in _send
    msg, mail_server_id=mail.mail_server_id.id, smtp_session=smtp_session)
  File "/usr/lib/python3/dist-packages/flectra/addons/base/ir/ir_mail_server.py", line 466, in send_email
    raise MailDeliveryException(_("Mail Delivery Failed"), msg)
flectra.addons.base.ir.ir_mail_server.MailDeliveryException: ('Mail Delivery Failed', "Mail delivery failed via SMTP server 'None'.\nSMTPSenderRefused: 530\n5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [MWHPR1001CA0013.namprd10.prod.outlook.com]\nbounce+6-res.users-10@iauctionco.com")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/flectra/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/flectra/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/flectra/addons/web/controllers/main.py", line 970, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/flectra/addons/web/controllers/main.py", line 962, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/flectra/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/flectra/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/flectra/addons/sales_team/models/res_users.py", line 17, in create
    user = super(ResUsers, self).create(vals)
  File "/usr/lib/python3/dist-packages/flectra/addons/note/models/res_users.py", line 14, in create
    user = super(Users, self).create(values)
  File "/usr/lib/python3/dist-packages/flectra/addons/auth_signup/models/res_users.py", line 147, in create
    user.with_context(create_user=True).action_reset_password()
  File "/usr/lib/python3/dist-packages/flectra/addons/auth_signup/models/res_users.py", line 138, in action_reset_password
    template.with_context(lang=user.lang).send_mail(user.id, force_send=True, raise_exception=True)
  File "/usr/lib/python3/dist-packages/flectra/addons/mail/models/mail_template.py", line 570, in send_mail
    mail.send(raise_exception=raise_exception)
  File "/usr/lib/python3/dist-packages/flectra/addons/mail/models/mail_mail.py", line 248, in send
    smtp_session.quit()
  File "/usr/lib/python3.5/smtplib.py", line 978, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.5/smtplib.py", line 419, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.5/smtplib.py", line 366, in putcmd
    self.send(str)
  File "/usr/lib/python3.5/smtplib.py", line 358, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

**Comment by parthivgls** [comment]
` smtplib.SMTPSenderRefused: (530, b'5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [MWHPR1001CA0013.namprd10.prod.outlook.com]', 'bounce+6-res.users-10@iauctionco.com')`

issue is regarding your SMTP server authentication and not with flectra.

**Comment by brandon72501** [comment]
Flectra says that the SMTP test passed.  Also, why would this keep the user from being created, just because an email could not be sent?

**Comment by parthivgls** [comment]
it actually sends out an email when user is created. and your server seems to be stopping the emails from being sent out. 

Testing does not confirm that SMTP server will let you send the email, it just check the validity of credentials.

**Comment by brandon72501** [comment]
I have the credential blank because I have an exchange connector setup to allow from our static IP and not credential based.  So I am assuming that if Flectra checking the credentials, then no credentials are required.  I would also assume that Flectra is reaching the server or the test would not show successful.

**Comment by brandon72501** [comment]
![image](https://user-images.githubusercontent.com/35106389/34576205-d5ad4560-f142-11e7-9866-a8291882ac15.png)

**Comment by brandon72501** [comment]
This has been rectified.  For a relay connection the actual MX pointer has to be used instead of the SMTP server dns.
